# Generated by Django 4.2.23 on 2025-08-08 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('user_group', models.CharField(choices=[('writing_a1', '写作 A-1'), ('writing_a2', '写作 A-2'), ('writing_b1', '写作 B-1'), ('writing_b2', '写作 B-2')], max_length=20, verbose_name='用户组别')),
                ('submitted_text', models.TextField(verbose_name='提交的文本内容')),
                ('fluency_score', models.IntegerField(default=0, verbose_name='流畅性分数')),
                ('flexibility_score', models.IntegerField(default=0, verbose_name='灵活性分数')),
                ('originality_score', models.IntegerField(default=0, verbose_name='原创性分数')),
                ('elaboration_score', models.IntegerField(default=0, verbose_name='详细性分数')),
                ('usefulness_score', models.IntegerField(default=0, verbose_name='实用性分数')),
                ('creativity_strategy_score', models.IntegerField(default=0, verbose_name='创意策略分数')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI完整回复')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
