# Generated by Django 4.2.23 on 2025-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_TTev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresult',
            name='creativity_strategy_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='elaboration_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='flexibility_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='fluency_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='originality_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='usefulness_score',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='character_depth_justification',
            field=models.TextField(blank=True, verbose_name='角色深度与共情解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='character_depth_score',
            field=models.IntegerField(default=0, verbose_name='角色深度与共情分数'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='conflict_depth_justification',
            field=models.TextField(blank=True, verbose_name='冲突深度与对抗性解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='conflict_depth_score',
            field=models.IntegerField(default=0, verbose_name='冲突深度与对抗性分数'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='narrative_craft_justification',
            field=models.TextField(blank=True, verbose_name='叙事技巧与视觉叙事解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='narrative_craft_score',
            field=models.IntegerField(default=0, verbose_name='叙事技巧与视觉叙事分数'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='overall_summary',
            field=models.TextField(blank=True, verbose_name='整体总结'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='plot_logic_justification',
            field=models.TextField(blank=True, verbose_name='情节逻辑与因果关系解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='plot_logic_score',
            field=models.IntegerField(default=0, verbose_name='情节逻辑与因果关系分数'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='story_structure_justification',
            field=models.TextField(blank=True, verbose_name='故事结构与转折点解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='story_structure_score',
            field=models.IntegerField(default=0, verbose_name='故事结构与转折点分数'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='thematic_expression_justification',
            field=models.TextField(blank=True, verbose_name='主题表达与思想论证解释'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='thematic_expression_score',
            field=models.IntegerField(default=0, verbose_name='主题表达与思想论证分数'),
        ),
    ]
