# Generated by Django 5.0.2 on 2025-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_TTev', '0002_remove_evaluationresult_creativity_strategy_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresult',
            name='character_depth_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='character_depth_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='conflict_depth_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='conflict_depth_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='narrative_craft_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='narrative_craft_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='plot_logic_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='plot_logic_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='story_structure_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='story_structure_score',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='thematic_expression_justification',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='thematic_expression_score',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='character_depth_arc_justification',
            field=models.TextField(blank=True, verbose_name='Character Depth & Moral Dilemma Arc Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='character_depth_arc_score',
            field=models.IntegerField(default=0, verbose_name='Character Depth & Moral Dilemma Arc Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='dual_resonance_ending_justification',
            field=models.TextField(blank=True, verbose_name='Dual Resonance of Ending: Personal & Public Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='dual_resonance_ending_score',
            field=models.IntegerField(default=0, verbose_name='Dual Resonance of Ending: Personal & Public Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='emotional_punch_aftershock_justification',
            field=models.TextField(blank=True, verbose_name='Emotional Punch & Aftershock Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='emotional_punch_aftershock_score',
            field=models.IntegerField(default=0, verbose_name='Emotional Punch & Aftershock Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='ethical_complexity_justification',
            field=models.TextField(blank=True, verbose_name='Institutional & Tech Ethical Complexity Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='ethical_complexity_score',
            field=models.IntegerField(default=0, verbose_name='Institutional & Tech Ethical Complexity Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='hierarchy_beats_design_justification',
            field=models.TextField(blank=True, verbose_name='Hierarchy of Beats & Midpoint/Climax Design Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='hierarchy_beats_design_score',
            field=models.IntegerField(default=0, verbose_name='Hierarchy of Beats & Midpoint/Climax Design Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='intergenerational_span_justification',
            field=models.TextField(blank=True, verbose_name='Intergenerational Span & Long-term Causality Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='intergenerational_span_score',
            field=models.IntegerField(default=0, verbose_name='Intergenerational Span & Long-term Causality Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='investigative_drive_justification',
            field=models.TextField(blank=True, verbose_name='Investigative Drive & Clue Architecture Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='investigative_drive_score',
            field=models.IntegerField(default=0, verbose_name='Investigative Drive & Clue Architecture Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='memory_anchors_justification',
            field=models.TextField(blank=True, verbose_name='Memory Anchors & Sensory Specificity Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='memory_anchors_score',
            field=models.IntegerField(default=0, verbose_name='Memory Anchors & Sensory Specificity Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='multi_layered_conflict_justification',
            field=models.TextField(blank=True, verbose_name='Multi-layered Conflict Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='multi_layered_conflict_score',
            field=models.IntegerField(default=0, verbose_name='Multi-layered Conflict Score'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='value_turns_cohesion_justification',
            field=models.TextField(blank=True, verbose_name='Value Turns & Causal Cohesion Justification'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='value_turns_cohesion_score',
            field=models.IntegerField(default=0, verbose_name='Value Turns & Causal Cohesion Score'),
        ),
    ]
